# Question 2

dbGetQuery(db, "ALTER TABLE Income RENAME TO Income_old")

# Create a table with SS_ID as primary key
dbSendQuery(conn = db, "CREATE TABLE Income
            (
            SS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
            AAGE INT,
            ACLSWKR TEXT,
            ADTIND TEXT,
            ADTOCC TEXT,
            AHGA TEXT,
            AHRSPAY NUM,
            AHSCOL TEXT,
            AMARITL TEXT,
            AMJIND TEXT,
            AMJOCC TEXT,
            ARACE TEXT,
            AREORGN TEXT,
            ASEX TEXT,
            AUNMEM TEXT,
            AUNTYPE TEXT,
            AWKSTAT TEXT,
            CAPGAIN NUM,
            CAPLOSS NUM,
            DIVVAL NUM,
            FILESTAT TEXT,
            GRINREG TEXT,
            GRINST TEXT,
            HDFMX TEXT,
            HHDREL TEXT,
            MARSUPWT NUM,
            MIGMTR1 TEXT,
            MIGMTR3 TEXT,
            MIGMTR4 TEXT,
            MIGSAME TEXT,
            MIGSUN TEXT,
            NOEMP NUM,
            PARENT TEXT,
            PEFNTVTY TEXT,
            PEMNTVTY TEXT,
            PENATVTY TEXT,
            PRCITSHP TEXT,
            SEOTR TEXT,
            VETQVA TEXT,
            VETYN TEXT,
            WKSWORK NUM,
            YEAR TEXT,
            TRGT TEXT)"
)

dbGetQuery(db, "INSERT INTO Income
           (
           AAGE,
           ACLSWKR,
           ADTIND,
           ADTOCC,
           AHGA,
           AHRSPAY,
           AHSCOL,
           AMARITL,
           AMJIND,
           AMJOCC,
           ARACE,
           AREORGN,
           ASEX,
           AUNMEM,
           AUNTYPE,
           AWKSTAT,
           CAPGAIN,
           CAPLOSS,
           DIVVAL,
           FILESTAT,
           GRINREG,
           GRINST,
           HDFMX,
           HHDREL,
           MARSUPWT,
           MIGMTR1,
           MIGMTR3,
           MIGMTR4,
           MIGSAME,
           MIGSUN,
           NOEMP,
           PARENT,
           PEFNTVTY,
           PEMNTVTY,
           PENATVTY,
           PRCITSHP,
           SEOTR,
           VETQVA,
           VETYN,
           WKSWORK,
           YEAR,
           TRGT
           )

           SELECT
           AAGE,
           ACLSWKR,
           ADTIND,
           ADTOCC,
           AHGA,
           AHRSPAY,
           AHSCOL,
           AMARITL,
           AMJIND,
           AMJOCC,
           ARACE,
           AREORGN,
           ASEX,
           AUNMEM,
           AUNTYPE,
           AWKSTAT,
           CAPGAIN,
           CAPLOSS,
           DIVVAL,
           FILESTAT,
           GRINREG,
           GRINST,
           HDFMX,
           HHDREL,
           MARSUPWT,
           MIGMTR1,
           MIGMTR3,
           MIGMTR4,
           MIGSAME,
           MIGSUN,
           NOEMP,
           PARENT,
           PEFNTVTY,
           PEMNTVTY,
           PENATVTY,
           PRCITSHP,
           SEOTR,
           VETQVA,
           VETYN,
           WKSWORK,
           YEAR,
           TRGT

           FROM Income_old;"
)

# Copying gave 598566 values
dbGetQuery(db, "DELETE FROM Income
           WHERE SS_ID > 199522;")

# Testing
dbReadTable(db, "Income")
